### ISSUE TITLE
Engine does not detect FUs when using InitEx

### ISSUE THREAD

**Issue by MathieuSteiner** [Fluigent/fgt-SDK#16]
The behavior is still to be confirmed (to be tested with a FB S/N > 9)
Using:

- LabVIEW 2019 32-bits and SDK 19.0.0.5
- a FB (S/N 359) with 4 FUs
- the example "Basic Get Instruments Info.vi"

No sensor channels is detected:
- fgt_get_sensorChannelCount returns a count of 0
- fgt_get_sensorChannelsInfo returns an error 11 (both are coherent)

Removing the call to fgt_initEx solves the FUs detection and all 4 Flow units are now properly seen

**Comment by MathieuSteiner** [comment]
Reproduced with FB S/N 1037
Replacing the InitEx by the Init method results in FUs being detected

**Comment by CristianGlavana** [comment]
Released version 19.0.0.6
https://github.com/Fluigent/fgt-SDK/releases/tag/19.0.0.6
