### ISSUE TITLE
LabVIEW "Basic Get Instruments Info" example error handling strategy

### ISSUE THREAD

**Issue by MathieuSteiner** [Fluigent/fgt-SDK#17]
The example stops as soon as an error is detected
This means that in case there is no pressure channels (no pressure controller for example), the example will stop and will not proceed to FB/FU detection (nor TTL channels detection)

Such behavior should be changed so that all types of channels should always be tested
Best solution is to:

- call fgt_get_pressureChannelsInfo only if fgt_get_pressureChannelCount returned at least one channel
- same schema to be applied for sensor/TTL channels

**Comment by CristianGlavana** [comment]
Released version 19.0.0.6
https://github.com/Fluigent/fgt-SDK/releases/tag/19.0.0.6
