### ISSUE TITLE
Fluigent | Matalb Control Code | Clemson University

### ISSUE THREAD

**Issue by omkarshukla10** [Fluigent/fgt-SDK#21]
Dear Mark and Team members, 

I am facing an issue with our Matlab control Code for the system we have at Clemson University.  The code written by us runs fine but suddenly it stops working in the middle at any instance of time. We have over 400 mixing test samples and the code stops randomly at 6th case or 1st or 2nd during our testing. I am worried about this and I would like to seek help from your software engineer regarding the issue. 

I am attaching our code along with this email for your reference. I am also attaching the error messages. Would you able to help us in solving this problem? 

![error_1](https://user-images.githubusercontent.com/58432408/69968737-03afa680-14e9-11ea-971b-4a1d950ac61e.png)
![error_2](https://user-images.githubusercontent.com/58432408/69968738-04483d00-14e9-11ea-8dd2-e93b908a09cb.png)

Let me know if your engineer requires a remote access to our system, we will be happy to provide the remote control of our system. 

Wishing you a Happy Thanksgiving, 
Omkar

-- attachement removed by Fluigent. There was a password in your code

**Comment by CristianGlavana** [comment]
Hello Omkar,

We are sorry that you are not having a smooth experience using your M-Switch valve.
Actually we are working on a software issue which can cause valve to block randomly, especially when many requests occur in little time. One inconvenient work around today is to remove the valve from the switchboard and plug it again.
We will keep you informed about the fix.

Best regards,
Cristian

**Comment by CristianGlavana** [comment]
New valve firmware fix this issue
