### ISSUE TITLE
LabVIEW wrapper 19.0.0.6 - fgt_SENSOR_Type - Missing L Dual in typeDef

### ISSUE THREAD

**Issue by gumen38** [Fluigent/fgt-SDK#24]
While working on a test bench, I realized that my FLOW UNIT L dual was detected as a FLOW UNIT XL
This is due to the fact that the typeDefed enumerated does not contain value 7

![LV_19 0 0 6_fgt_SENSOR_Type_Missing_L_Dual](https://user-images.githubusercontent.com/35495042/92090694-04ef6600-edd0-11ea-84aa-8da03e027079.PNG)

**Comment by CristianGlavana** [comment]
Flow unit L is implemented for both single and dual types. Maybe LabVIEW enum is shifted as value 7 corresponds to L_dual and 8 to XL_single. in the dll API

**Comment by gumen38** [comment]
> Flow unit L is implemented for both single and dual types. Maybe LabVIEW enum is shifted as value 7 corresponds to L_dual and 8 to XL_single. in the dll API

The issue lies in the typeDef that misses one value. Not in the SDK core

**Comment by CristianGlavana** [comment]
Fixed version 20.0.0.0 #26
