### ISSUE TITLE
ess valve movement confirmation

### ISSUE THREAD

**Issue by jmschreiner** [Fluigent/fgt-SDK#27]
I have a software question about the ESS valve SDK for the project we're working on.  We would like to positively confirm that the valves are in the correct position before starting flow, but the SDK does not provide such a query.  So, I have two questions:
- Can we assume that by the time the function to set the position (ess_set_rot_switch / ess_set_two_switch) returns, that the valve is already in the requested position and not still moving?
- If the valve fails to reach the requested position for some reason, will a non-zero value be returned?  The return values listed in ess_c.h don't seem that they would indicate such an error.

**Comment by Ygor-Oliveira** [comment]
Hello,

The shared library functions are non-blocking. They return immediately
after sending the command to the instrument, only returning an error if the
arguments are invalid or if there is a connection problem.

To wait for the valve to reach the specified position, you can call
`ess_get_data_rot_switch` or `ess_get_data_two_switch` every 50ms in a loop
until the position matches what you requested.
