### ISSUE TITLE
fgt_set_sensorRegulationResponse not functional for vacuum-driven flow control.

### ISSUE THREAD

**Issue by tedstertm** [Fluigent/fgt-SDK#3]
The sensor-based flow control defaults to a positive pressure based feedback. My instrument uses vacuum. As a result the fgt_set_sensorRegulationResponse function provides feedback inverse of what it needs to be to get to the appropriate flowrate.

**Comment by CristianGlavana** [comment]
In most cases, sensor sense points out from the reservoir. This is the expected logic of the regulation algorithm. Thus there is an exception on vacuum MFCS™ Series instruments, sensor sense has to be inverted from nominal case: sensor has to point towards the reservoir.
MFCS instruments are always seen with positive range, enven if vacuum.

**Comment by CristianGlavana** [comment]
In case you do not want to change the set-up, sensor can be tricked by applying a scale factor: fgt_set_sensorCustomScale(sensorIndex, -1, 0 ,0);

**Comment by tedstertm** [comment]
I changed the scale as suggested but am no longer getting sensor readings in µL/min, but as some very long number. Is there a correction that I can apply elsewhere to correct this?

**Comment by CristianGlavana** [comment]
An update was pushed on master branch. After investigation and testing in same conditions there seem to be no issue. After clonning could you please run the example Basic Sensor Regulation.cpp and send a screenshot of displayed terminal, this way we can deeper investigate if needed.

**Comment by CristianGlavana** [comment]
Thank you for provided feedback and for participating on beta version. First release 19.0.0 is now available.
This issue will be closed but feel free to contact us for any question.
