### ISSUE TITLE
fluigent MFSC - triangle waveform with time

### ISSUE THREAD

**Issue by tomigaya31** [Fluigent/fgt-SDK#40]
Hello, 
I would like to program a triangle function that will set and read the pressure with time at 1Hz, 2Hz, 10Hz, eventually 100Hz. I use Labview library, but I would like to simplify the instruction to go faster with MFSC. However the set/read vi are locked. 
Is it possible to access the most direct command to set a pressure on MFSC on channel 1 only ? 
(if it is not clear : a function generator is giving an output voltage versus time, at different frequencies. Here, I would like the voltage to become the pressure on MFSC). 
Yours
Laurent

**Comment by mtrellet** [comment]
@tomigaya31 Did it answer your question? Can I close the issue?
