### ISSUE TITLE
LineUP series devices not detected when running code from Ubuntu

### ISSUE THREAD

**Issue by ayak2002** [Fluigent/fgt-SDK#44]
I wrote Python code that works fine when I run it from PyCharm on my Windows machine. It still runs when I run the same scripts from Ubuntu, but it does not detect the Fluigent instruments at all even though my machine satisfies all the requirements in the fgt-SDK manual. I've tried a bunch of online solutions and none of them worked, so I'm not sure what to do next.

**Comment by radoslawik** [comment]
Hello,

It could be the problem with [permissions](https://github.com/Fluigent/fgt-SDK#linux-permissions) to access to peripheral devices. Does executing [this script](https://github.com/Fluigent/fgt-SDK/blob/master/linux-udev.sh) as superuser (with `sudo`) solve the problem?

**Comment by mtrellet** [comment]
Hello @ayak2002,

Just to be sure, do we agree that the exact same script detects the Fluigent instruments properly when run on Windows from PyCharm?
Would you mind posting a snippet of your code and, ideally, the output of it here?

Another possible way to troubleshoot your issue would be to use OxyGEN and check whether your instruments show up there:
https://www.fluigent.com/resources-support/support-tools/software/oxygen/

**Comment by ayak2002** [comment]
Hello again @mtrellet ,

Yes, the exact same code runs on Windows from PyCharm, but not from Ubuntu. 
It's simple code that says whether a controller is detected, prints the pump's information, and sets a pressure for it.
It works as expected if I run it from PyCharm, but when I turn it into an executable and run it from Ubuntu the output shows that no controllers have been detected, and I get the "No instr found" warning.

**Comment by mtrellet** [comment]
> It works as expected if I run it from PyCharm, but when I turn it into an executable and run it from Ubuntu

Did you try running the code directly and not from the executable?

To go further, would you mind running those few commands and send back their output?

```
lsusb -v -d 04d8:
ls -lh /dev/hid*
ls /dev/hid* | xargs -n 1 hexdump -n 64
ls /dev/hid* | xargs -n 1 udevadm info
```

That will help see whether the system detects the instruments already and is able to read their info.

**Comment by ayak2002** [comment]
Hello again,

Running the code directly led to the same issue. I also tried running the
commands you wanted me to run, and it doesn't seem I'm getting the expected
output either:
[image: image.png]

**Comment by mtrellet** [comment]
Hello,

I cannot see the image you attached, you you mind copy/pasting the output? Re-attaching the image directly from github might also work.

Thanks

**Comment by mtrellet** [comment]
Results of the commands seem to indicate that your OS do not even see the devices that are connected. This will of course prevent any communication between the SDK and the instruments.

Are you using Ubuntu within a Virtual Machine or is it a native installation on a dedicated computer? Did you try restarting your computer with the instruments connected to it?

**Comment by mtrellet** [comment]
Can you check that this file was successfully created: `/etc/udev/rules.d/99-fluigent.rules`
And that it is not empty?

**Comment by ayak2002** [comment]
The file exists, here are its contents:
# Enable access to Fluigent instruments without superuser rights
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0000",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0001",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0002",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0003",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0010",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0012",
MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="0017",
MODE="0666"

**Comment by ayak2002** [comment]
Sorry for the multiple messages, just wanted to let you know that going
through the solutions you had given me for my laptop worked on the
raspberry pi! I'm still not sure what could have caused the problems when
running the code from my laptop though...

**Comment by mtrellet** [comment]
That's some good news! 
We are still puzzled by the issue you encountered with Ubuntu though... I'll close the issue for the time being, we will monitor further issues people might encounter with Ubuntu in the future.

Thanks for your time!
