### ISSUE TITLE
Sensor Calibration

### ISSUE THREAD

**Issue by ayak2002** [Fluigent/fgt-SDK#46]
Hello, I have been trying to set the flow rate for my system from the software development kit functions using the fluigent LineUp pressure pumps and Flow units. I am running droplet generation oil with one pump and water with the other. I am running into an issue where whatever flow unit I use to regulate the flow rate of the water is oscillating a lot around the flow rate I need instead of being more or less constant with very small oscillations. The other flow unit that has oil running through it is not causing this issue. I know that it is only for the water because I have tried switching flow units and the issue keeps repeating for whatever unit has water flowing through it. I already tried checking the calibration table of each of my flow units using the function present in the software development kit, and it says both flow units are set to H2O. I am not sure what could be causing this problem.

**Comment by mtrellet** [comment]
Hello @ayak2002 ,

Would you mind giving us the type of FlowUnit you are using (S,M,L, etc.) and the flow-rate value you are trying to reach? Do you have an estimation of the oscillations amplitude?

Thanks in advance!

**Comment by ayak2002** [comment]
Hello,

I am using type M flow units. I was trying to reach a flow rate of 5
uL/min, but the oscillations were still happening for much higher flow
rates such as 20 uL/min.
I do not remember exactly how big the oscillations were, but I do remember
them going at least 3 uL/min above or below the required value (sometimes
higher).

Thank you

**Comment by mtrellet** [comment]
Hello @ayak2002 ,

I believe you have been in touch with our support team in parallel, can I close this issue?
