### ISSUE TITLE
Python code with Linux and ARM processor

### ISSUE THREAD

**Issue by eeycn** [Fluigent/fgt-SDK#48]
I am trying to use the controller with a single-board computer. Does the python code work with Linux OS and ARM processor?

**Comment by Ygor-Oliveira** [comment]
It should work, if the Linux distribution is recent enough. Please check the requirements in the main page: https://github.com/Fluigent/fgt-SDK#supported-operating-systems-and-architectures

**Comment by mtrellet** [comment]
@eeycn Could you successfully achieve what you wanted? Can I close the issue?

**Comment by eeycn** [comment]
Yes
