### ISSUE TITLE
SDK library installation

### ISSUE THREAD

**Issue by eeycn0128** [Fluigent/fgt-SDK#58]
Hi,

For the fluigent_sdk-22.0.0, how could I install the library for python? Since there are two files that needed to be installed (.exe and .msi), is there any sequence requirement for the packages?

**Comment by Ygor-Oliveira** [comment]
Hello,

You do not need to use both installers. You can choose either the .msi or the .exe, or the .zip which is compatible with all supported operating systems. The command to install using the the .zip file is in the [manual](https://raw.githubusercontent.com/Fluigent/fgt-SDK/22.1.0.0/Fluigent%20SDK.pdf#subsection.4.3.3). We only provide all options in case some users prefer one or the other, but we might remove the Windows-only installers for future releases to avoid confusion, as this distribution method has been deprecated by Python itself.

Also, please make sure you use the [latest release](https://github.com/Fluigent/fgt-SDK/releases/latest), especially if you have recently-bought instruments, as the older releases might not support them correctly or at all.

Best,
Ygor
