### ISSUE TITLE
New user/Software crash with Aria

### ISSUE THREAD

**Issue by graghun** [Fluigent/fgt-SDK#67]
Hi, I'm a new user trying to use Aria for some flow applications. We are interested in flow control from TTL pulses generated by our microscope; and currently, I'm having issues with the dedicated Aria application. 

The software detects the Aria hardware, but the moment I try adding/editing the existing sequence, the software crashes with no apparent error messages. I can access other sub-menus, such as going to the calibration window, manipulating TTL pulse duration, etc. I'm running this on a Win 11/ i7 7th gen laptop (FYI).

Any help on this would be appreciated.

**Comment by mtrellet** [comment]
Hello @graghun ,

The SDK does not currently support Aria currently so this issue tracker might not be the ideal place for Aria-related issues. Could you please contact support@fluigent.com about your problem please? 
In your message please provide the Aria software version you are currently using and the Aria instrument SN please.

Best,

Mikael
