### ISSUE TITLE
calling fgt_set_pressure causes unhandelable exception

### ISSUE THREAD

**Issue by VincentBressler** [Fluigent/fgt-SDK#7]
This is intermittent behavior. Adding a delay before calling the function does not fix the problem. 

I am using DLLs that I downloaded from here today:
https://github.com/Fluigent/fgt-SDK/archive/master.zip

**Comment by CristianGlavana** [comment]
Did you have this issue before? Changes on the library did not cencern fgt_set_pressure function.
We are proceeding final tests for a release next week. Sending over 3million consecutive orders, without delay caused no problem. Dll also supports multithreading. Does this happen with the basic example?
If you have additional information it is welcomed. For now we may need more time to investigate for such issue.
Thank you

**Comment by VincentBressler** [comment]
I believe that this behavior is new. I'll do some testing to confirm.

**Comment by VincentBressler** [comment]
The problem has been around for at least a month. Here is the sequence of calls which intermittently cause the problem:
![image](https://user-images.githubusercontent.com/51495265/61552394-91906680-aa0c-11e9-8cf5-18bc25e1db04.png)

**Comment by VincentBressler** [comment]
I have absolutely confirmed that the exception occurs inside a call to pfgt_set_pressure.
I have put exception handling round this function call using both

__try  and try

Exception handling does not work in either case. It's almost as if an ExitProcess() call is happening somewhere in your code.

**Comment by VincentBressler** [comment]
Improved logging, included the pressure value being set:
![image](https://user-images.githubusercontent.com/51495265/61552740-7d009e00-aa0d-11e9-9855-ecbb4301f053.png)

**Comment by VincentBressler** [comment]
Adding long delays (10 seconds or more) after set_sensorRegulation () does not make any difference.
Adding long delays (1 second) before each call to set_pressure() does not make any difference.

I got rid of these delays because they simply slow down debugging.

**Comment by CristianGlavana** [comment]
Thank you for the much provided details.
Indeed an exception is randomly thrown when regulation is running and pressure orders are send. A concurrent ressource was used in this case.
Libraries are recompiled with apropriate synchronisation. It is now available on master branch.

Please feel free to contact us if any question.
Thank you for the detailed feed back and for your colaboration!

**Comment by VincentBressler** [comment]
Thanks! I have confirmed that the new version of: 
fgt_SDK_64.dll 
fixes the problem.

**Comment by CristianGlavana** [comment]
Thank you for provided feedback and for participating on beta version. First release 19.0.0 is now available.
This issue will be closed but feel free to contact us for any question.
