### ISSUE TITLE
how to use fgt_create_simulated_instr?

### ISSUE THREAD

**Issue by time4Wiley** [Fluigent/fgt-SDK#76]
how to use fgt_create_simulated_instr? some examples will be great.

**Comment by Ygor-Oliveira** [comment]
Hello,

The documentation for the simulated instrument configuration is in chapter 7 of the manual:

<https://raw.githubusercontent.com/Fluigent/fgt-SDK/23.0.0/Fluigent%20SDK.pdf#chapter.7>

We are planning to add an example for the next release.
Best regards,
Ygor

**Comment by time4Wiley** [comment]
great. I can work with simulated instruments now. the SDK pdf is clear enough.
